# Generated by Django 3.1.3 on 2020-11-19 02:23

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('venue_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='role',
            name='id',
        ),
        migrations.AlterField(
            model_name='role',
            name='role_num',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='venue_system.customuser')),
                ('seat_rows', models.PositiveIntegerField()),
                ('seat_cols', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=75)),
                ('mpoly', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='role_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='venue_system.role'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('concert_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='venue_system.customuser')),
                ('venue_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='venue_system.venue')),
            ],
            options={
                'unique_together': {('artist_id', 'date_time')},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField()),
                ('seat_row', models.PositiveIntegerField()),
                ('seat_col', models.PositiveIntegerField()),
                ('concert_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='venue_system.concert')),
                ('customer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='venue_system.customuser')),
            ],
            options={
                'unique_together': {('seat_col', 'seat_col', 'concert_id')},
            },
        ),
        migrations.CreateModel(
            name='SeatRank',
            fields=[
                ('seat_rank_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('seat_rank', models.CharField(max_length=5)),
                ('seat_row', models.PositiveIntegerField()),
                ('seat_col', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('venue_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='venue_system.venue')),
            ],
        ),
    ]
